ALTER TABLE clientUser ADD foreign key (client_id) references user(user_id) on delete cascade;
ALTER TABLE customer ADD foreign key (customer_id) references user(user_id) on delete cascade;
ALTER TABLE address ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE seller ADD foreign key (seller_id) references user(user_id) on delete cascade;
ALTER TABLE adminUser  ADD foreign key (admin_id) references user(user_id) on delete cascade;
ALTER TABLE shopContact  ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE review  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE review  ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE product  ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE productCategory  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE productCategory  ADD foreign key (category_id) references category(category_id) on delete cascade;
ALTER TABLE pictureurl  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE orderItem  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE orderItem  ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE orderItem  ADD foreign key (order_id) references ordert(order_id) ON DELETE SET NULL;
ALTER TABLE ordert  ADD foreign key (payment_id) references payment(payment_id) ON DELETE SET NULL;
ALTER TABLE payment  ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE report  ADD foreign key (user_id) references user(user_id) on delete cascade;
ALTER TABLE promotion  ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE sellerAdvertisement ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE sponsorAdvertisement ADD foreign key (sponsor_id) references sponsor(sponsor_id) on delete cascade;
