ALTER TABLE client_user ADD foreign key (client_id) references user(user_id) on delete cascade;
ALTER TABLE customer ADD foreign key (customer_id) references user(user_id) on delete cascade;
ALTER TABLE address ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE seller ADD foreign key (seller_id) references user(user_id) on delete cascade;
ALTER TABLE admin_user  ADD foreign key (admin_id) references user(user_id) on delete cascade;
ALTER TABLE shopContact  ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE review  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE review  ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE product  ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE product_category  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE product_category  ADD foreign key (category_id) references category(category_id) on delete cascade;
ALTER TABLE pictureurl  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE order_item  ADD foreign key (product_id) references product(product_id) on delete cascade;
ALTER TABLE order_item  ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE order_item  ADD foreign key (order_id) references ordert(order_id);
ALTER TABLE ordert  ADD foreign key (payment_id) references payment(payment_id);
ALTER TABLE payment  ADD foreign key (customer_id) references customer(customer_id) on delete cascade;
ALTER TABLE report  ADD foreign key (user_id) references user(user_id) on delete cascade;
ALTER TABLE promotion  ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE seller_advertisement ADD foreign key (seller_id) references seller(seller_id) on delete cascade;
ALTER TABLE sponsor_advertisement ADD foreign key (sponsor_id) references sponsor(sponsor_id) on delete cascade;
